### ISSUE TITLE
Add package to auto group

### ISSUE THREAD

**Issue by muuvmuuv** [stormwarning/stylelint-config-recess-order#265]
Would be cool to have a separate package that allows grouping with empty lines.

```scss
a {
  position: relative;
  box-sizing: inherit;
}
```

becomse:

```scss
a {
  position: relative;

  box-sizing: inherit;
}
```
