### ISSUE TITLE
Font properties end up in between padding and border

### ISSUE THREAD

**Issue by ArianeBouchardConformit** [stormwarning/stylelint-config-recess-order#380]
I have a Sass mixin, and for some reason, using this preset, font/text properties go between padding and border. That seems to make no sense to me. The rules don't even seem to call for that. I'm confused.

Before linting:

```scss
@mixin table-cell-reset {
   padding: 0;
   border: 0;
   font-weight: 400;
   text-align: left;
}
```

After linting:

```scss
@mixin table-cell-reset {
   padding: 0; 
   font-weight: 400;
   text-align: left;
   border: 0;
}
```

Here's my stylelint.config.mjs file:

```javascript
const SEVERITIES = {
   error: 'error',
   warning: 'warning',
}

const STYLELINT_CONFIG = {
   extends: [
      'stylelint-config-recommended',
      'stylelint-config-standard-scss',
      'stylelint-config-standard-vue/scss',
      'stylelint-config-recess-order',
   ],
   overrides: [
      {
         files: [
            '*.vue',
            '**/*.vue',
            '*.scss',
            '**/*.scss',
         ],
         rules: {
            'property-disallowed-list': [ [ 'flex', 'background', 'font' ], { severity: SEVERITIES.error } ],
            'color-named': [ 'never', { severity: SEVERITIES.warning } ],
            'color-no-hex': [ true, { severity: SEVERITIES.warning } ],
            'declaration-no-important': [ true, { severity: SEVERITIES.warning } ],
         },
      },
   ],
}

export default STYLELINT_CONFIG
```

Here are some package versions from my package-lock.json:

- stylelint 16.8.2
- stylelint-config-recommended 14.0.1
- stylelint-config-recess-order 5.1.0
- stylelint-config-html 1.1.0
- stylelint-config-recommended-scss 14.1.0
- stylelint-config-recommended-vue 1.5.0
- stylelint-config-standard 36.0.1
- stylelint-config-standard-scss 13.1.0
- stylelint-config-standard-vue 1.0.0
- stylelint-order 6.0.4
- stylelint-scss 6.5.1
- postcss 8.4.41
